# -- Namespace where the operator will be installed.
# Defaults to .Release.Namespace
namespaceOverride: ""
# -- Image to use for the OLM components.
image: quay.io/operator-framework/olm@sha256:e74b2ac57963c7f3ba19122a8c31c9f2a0deb3c0c5cac9e5323ccffd0ca198ed
packageserver:
  tls:
    # -- Type of TLS certificates. Supported values are "helm" and "cert-manager".
    # For production setup, it is recommended to use "cert-manager".
    type: "helm"
    # -- CA certificate for the PackageServer APIService. Overrides the tls.type setting.
    caCert: ""
    # -- Client certificate for the PackageServer APIService. Overrides the tls.type setting.
    tlsCert: ""
    # -- Client key for the PackageServer APIService. Overrides the tls.type setting.
    tlsKey: ""